import type { ThemePreset } from '@/types/theme';

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'rose-pink',
    name: '로즈 핑크',
    nameEn: 'Rose Pink',
    description: '사랑스럽고 여성스러운 핑크 톤',
    emoji: '🩷',
    isDark: false,
    colors: {
      primary: '#F472B6',
      primaryLight: '#FCE7F3',
      primaryDark: '#DB2777',
      secondary: '#FDF2F8',
      accent: '#EC4899',
      background: '#FFF5F7',
      surface: '#FFFFFF',
      surfaceAlt: '#FDF2F8',
      text: '#1A1A2E',
      textSecondary: '#4B5563',
      textMuted: '#9CA3AF',
      border: '#FCE7F3',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
    },
  },
  {
    id: 'soft-ivory',
    name: '소프트 아이보리',
    nameEn: 'Soft Ivory',
    description: '따뜻하고 자연스러운 아이보리 톤',
    emoji: '🤍',
    isDark: false,
    colors: {
      primary: '#D4B896',
      primaryLight: '#F7F0E6',
      primaryDark: '#A8895F',
      secondary: '#F0E8D8',
      accent: '#C4A882',
      background: '#FFFDF7',
      surface: '#FFFFFF',
      surfaceAlt: '#F7F0E6',
      text: '#3D3427',
      textSecondary: '#6B5E4F',
      textMuted: '#A89880',
      border: '#EDE0CE',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
    },
  },
  {
    id: 'clean-black',
    name: '클린 블랙',
    nameEn: 'Clean Black',
    description: '깔끔한 블랙 & 그레이 무채색 톤',
    emoji: '🖤',
    isDark: false,
    colors: {
      primary: '#0F172A',
      primaryLight: '#1E293B',
      primaryDark: '#020617',
      secondary: '#9CA3AF',
      accent: '#6B7280',
      background: '#FFFFFF',
      surface: '#F8FAFC',
      surfaceAlt: '#F1F5F9',
      text: '#0F172A',
      textSecondary: '#475569',
      textMuted: '#94A3B8',
      border: '#E2E8F0',
      success: '#22C55E',
      warning: '#F59E0B',
      error: '#EF4444',
    },
  },
  {
    id: 'olive-green',
    name: '올리브 그린',
    nameEn: 'Olive Green',
    description: '자연스럽고 차분한 올리브 톤',
    emoji: '🫒',
    isDark: false,
    colors: {
      primary: '#84A98C',
      primaryLight: '#DAE8DC',
      primaryDark: '#52796F',
      secondary: '#CAD2C5',
      accent: '#74A57F',
      background: '#F2F7F3',
      surface: '#FFFFFF',
      surfaceAlt: '#E8F0EA',
      text: '#2D3B2D',
      textSecondary: '#4A5C4A',
      textMuted: '#84A98C',
      border: '#CAD2C5',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
    },
  },
  {
    id: 'pastel-blue',
    name: '파스텔 블루',
    nameEn: 'Pastel Blue',
    description: '차분하고 시원한 하늘빛',
    emoji: '💙',
    isDark: false,
    colors: {
      primary: '#93C5FD',
      primaryLight: '#BFDBFE',
      primaryDark: '#60A5FA',
      secondary: '#60A5FA',
      accent: '#3B82F6',
      background: '#FFFFFF',
      surface: '#F0F7FF',
      surfaceAlt: '#E8F2FF',
      text: '#1E3A5F',
      textSecondary: '#4A6FA5',
      textMuted: '#8CB4D5',
      border: '#D4E6F7',
      success: '#22C55E',
      warning: '#F59E0B',
      error: '#EF4444',
    },
  },
  {
    id: 'pastel-lilac',
    name: '파스텔 라일락',
    nameEn: 'Pastel Lilac',
    description: '부드럽고 우아한 연보라',
    emoji: '💜',
    isDark: false,
    colors: {
      primary: '#C4B5FD',
      primaryLight: '#DDD6FE',
      primaryDark: '#A78BFA',
      secondary: '#A78BFA',
      accent: '#8B5CF6',
      background: '#FFFFFF',
      surface: '#F5F3FF',
      surfaceAlt: '#EDE9FE',
      text: '#3B1F6E',
      textSecondary: '#6D5A9E',
      textMuted: '#A99BC7',
      border: '#E0D5F5',
      success: '#22C55E',
      warning: '#F59E0B',
      error: '#EF4444',
    },
  },
  {
    id: 'pastel-pink',
    name: '파스텔 핑크',
    nameEn: 'Pastel Pink',
    description: '부드럽고 달콤한 핑크 톤',
    emoji: '🌸',
    isDark: false,
    colors: {
      primary: '#F9A8D4',
      primaryLight: '#FCE7F3',
      primaryDark: '#EC4899',
      secondary: '#FBCFE8',
      accent: '#F472B6',
      background: '#FFF5F9',
      surface: '#FFFFFF',
      surfaceAlt: '#FDF2F8',
      text: '#4A1942',
      textSecondary: '#7A3B6E',
      textMuted: '#C084B0',
      border: '#F9D4E8',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
    },
  },
  {
    id: 'pastel-mint',
    name: '파스텔 민트',
    nameEn: 'Pastel Mint',
    description: '상쾌하고 시원한 민트 톤',
    emoji: '🍃',
    isDark: false,
    colors: {
      primary: '#6EE7B7',
      primaryLight: '#D1FAE5',
      primaryDark: '#34D399',
      secondary: '#A7F3D0',
      accent: '#10B981',
      background: '#F0FDF9',
      surface: '#FFFFFF',
      surfaceAlt: '#ECFDF5',
      text: '#134E3A',
      textSecondary: '#3B7A5E',
      textMuted: '#86C4A8',
      border: '#C6F0DE',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
    },
  },
  {
    id: 'pastel-yellow',
    name: '파스텔 옐로우',
    nameEn: 'Pastel Yellow',
    description: '따뜻하고 화사한 옐로우 톤',
    emoji: '🌼',
    isDark: false,
    colors: {
      primary: '#FCD34D',
      primaryLight: '#FEF3C7',
      primaryDark: '#F59E0B',
      secondary: '#FDE68A',
      accent: '#FBBF24',
      background: '#FFFDF5',
      surface: '#FFFFFF',
      surfaceAlt: '#FEF9E7',
      text: '#4A3C10',
      textSecondary: '#7A6B30',
      textMuted: '#C4B060',
      border: '#F5E8B4',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
    },
  },
  {
    id: 'pastel-mix',
    name: '파스텔 믹스',
    nameEn: 'Pastel Mix',
    description: '핑크, 민트, 옐로우가 어우러진 파스텔 톤',
    emoji: '🎀',
    isDark: false,
    colors: {
      primary: '#F9A8D4',
      primaryLight: '#FCE7F3',
      primaryDark: '#EC4899',
      secondary: '#6EE7B7',
      accent: '#FCD34D',
      background: '#FFFAF5',
      surface: '#FFFFFF',
      surfaceAlt: '#FFF0F5',
      text: '#3D2B3A',
      textSecondary: '#6B5568',
      textMuted: '#B89AAE',
      border: '#F5DDE8',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
    },
  },
];

export const DEFAULT_THEME_ID = 'rose-pink';

export function getThemeById(id: string): ThemePreset {
  return THEME_PRESETS.find((t) => t.id === id) ?? THEME_PRESETS[0];
}
