import type { ThemePreset } from '@/types/theme';

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'pastel-pink',
    name: '파스텔 핑크',
    nameEn: 'Pastel Pink',
    description: '부드럽고 달콤한 핑크 톤',
    emoji: '🌸',
    isDark: false,
    colors: {
      primary: '#FDCFE8',
      primaryLight: '#FEF0F7',
      primaryDark: '#F9A8D4',
      secondary: '#FEE5F2',
      accent: '#FAB8D9',
      background: '#FFFAFB',
      surface: '#FFFFFF',
      surfaceAlt: '#FFF5FA',
      text: '#5C2854',
      textSecondary: '#8E5A82',
      textMuted: '#D4A6C6',
      border: '#FDE4F0',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
    },
  },
  {
    id: 'rose-pink',
    name: '로즈 핑크',
    nameEn: 'Rose Pink',
    description: '사랑스럽고 여성스러운 핑크 톤',
    emoji: '🩷',
    isDark: false,
    colors: {
      primary: '#F9A8D4',
      primaryLight: '#FEF0F7',
      primaryDark: '#F472B6',
      secondary: '#FFF0F7',
      accent: '#F9A8D4',
      background: '#FFFAFB',
      surface: '#FFFFFF',
      surfaceAlt: '#FFF5FA',
      text: '#2D1A35',
      textSecondary: '#5C4A64',
      textMuted: '#B0A0B8',
      border: '#FDE8F3',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
    },
  },
  {
    id: 'pure-ivory',
    name: '퓨어 아이보리',
    nameEn: 'Pure Ivory',
    description: '우아하고 깨끗한 아이보리 화이트 톤',
    emoji: '🤍',
    isDark: false,
    colors: {
      primary: '#C8B8A2',
      primaryLight: '#F8F4EF',
      primaryDark: '#9E8E78',
      secondary: '#F0E8DD',
      accent: '#B5A48E',
      background: '#FFFFFB',
      surface: '#FEFEFE',
      surfaceAlt: '#FAF7F2',
      text: '#4A443D',
      textSecondary: '#7A7064',
      textMuted: '#B5AC9F',
      border: '#F0EAE2',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
    },
  },
  {
    id: 'soft-ivory',
    name: '소프트 베이지',
    nameEn: 'Soft Beige',
    description: '따뜻하고 자연스러운 베이지 톤',
    emoji: '🤎',
    isDark: false,
    colors: {
      primary: '#DFC8AE',
      primaryLight: '#FAF5EE',
      primaryDark: '#BCA27A',
      secondary: '#F5EDE0',
      accent: '#D0BA9E',
      background: '#FFFEFB',
      surface: '#FFFFFF',
      surfaceAlt: '#FAF5EE',
      text: '#4D4538',
      textSecondary: '#7D7060',
      textMuted: '#BAA88E',
      border: '#F2E8D8',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
    },
  },
  {
    id: 'clean-black',
    name: '클린 블랙',
    nameEn: 'Clean Black',
    description: '깔끔한 블랙 & 그레이 무채색 톤',
    emoji: '🖤',
    isDark: false,
    colors: {
      primary: '#1E293B',
      primaryLight: '#E8EDF3',
      primaryDark: '#0F172A',
      secondary: '#B0B8C4',
      accent: '#7C8594',
      background: '#FFFFFF',
      surface: '#FAFBFD',
      surfaceAlt: '#F4F6F9',
      text: '#1E293B',
      textSecondary: '#5A6A7E',
      textMuted: '#A4B0C0',
      border: '#E8EDF3',
      success: '#22C55E',
      warning: '#F59E0B',
      error: '#EF4444',
    },
  },
  {
    id: 'olive-green',
    name: '올리브 그린',
    nameEn: 'Olive Green',
    description: '자연스럽고 차분한 올리브 톤',
    emoji: '🫒',
    isDark: false,
    colors: {
      primary: '#9DBBA4',
      primaryLight: '#E4EEE6',
      primaryDark: '#6B9A78',
      secondary: '#D6DED0',
      accent: '#8DB898',
      background: '#F6FAF7',
      surface: '#FFFFFF',
      surfaceAlt: '#EEF4F0',
      text: '#3D4D3D',
      textSecondary: '#5C6E5C',
      textMuted: '#B4CCB8',
      border: '#D6DED0',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
    },
  },
  {
    id: 'pastel-blue',
    name: '파스텔 블루',
    nameEn: 'Pastel Blue',
    description: '차분하고 시원한 하늘빛',
    emoji: '💙',
    isDark: false,
    colors: {
      primary: '#B4D8FE',
      primaryLight: '#D4EAFE',
      primaryDark: '#82B8FC',
      secondary: '#82B8FC',
      accent: '#5AA0F8',
      background: '#FFFFFF',
      surface: '#F5FAFF',
      surfaceAlt: '#EDF5FF',
      text: '#2E4A6F',
      textSecondary: '#5E82B5',
      textMuted: '#A0C4DE',
      border: '#DEE9F8',
      success: '#22C55E',
      warning: '#F59E0B',
      error: '#EF4444',
    },
  },
  {
    id: 'pastel-lilac',
    name: '파스텔 라일락',
    nameEn: 'Pastel Lilac',
    description: '부드럽고 우아한 연보라',
    emoji: '💜',
    isDark: false,
    colors: {
      primary: '#D6CAFE',
      primaryLight: '#E8E2FE',
      primaryDark: '#BAA2FC',
      secondary: '#BAA2FC',
      accent: '#A07AF8',
      background: '#FFFFFF',
      surface: '#F8F6FF',
      surfaceAlt: '#F2EEFE',
      text: '#4D2F7E',
      textSecondary: '#7F6AAE',
      textMuted: '#BBB0D4',
      border: '#EAE0F8',
      success: '#22C55E',
      warning: '#F59E0B',
      error: '#EF4444',
    },
  },
];

export const DEFAULT_THEME_ID = 'pastel-pink';

export function getThemeById(id: string): ThemePreset {
  return THEME_PRESETS.find((t) => t.id === id) ?? THEME_PRESETS[0];
}
